
export const environment = {
  production: false,
  firebaseConfig: {
    apiKey: "AIzaSyDaY1a8pb6kbgO6apkUVqnQjZAt87F0uRQ",
    authDomain: "multitask-web.firebaseapp.com",
    databaseURL: "https://multitask-web.firebaseio.com",
    projectId: "multitask-web",
    storageBucket: "multitask-web.appspot.com",
    messagingSenderId: "1091635374212",
    appId: "1:1091635374212:web:64d0ba31668236c0ccfad1",
    measurementId: "G-Y87CBVERHZ"
  },
  TABLAS: {
    acreedores: 'acreedores',
    baterias: 'baterias',
    categorias: 'categorias',
    consultas: 'consultas',
    cotizacion_dolar: 'cotizacion_dolar',
    deudores: 'deudores',
    displays: 'displays',
    equipos_vendidos: 'equipos_vendidos',
    flexs: 'flexs',
    ingresosBrutos: 'ingresosBrutos',
    modulos: 'modulos',
    otrosRepuestos: 'otrosRepuestos',
    pedidos: 'pedidos',
    productos: 'productos',
    stockModulos: 'stockModulos',
    tactiles: 'tactiles',
    users: 'users',
    tareasEmpleados: 'tareasEmpleados',
    categoriasProductos: 'categoriasProductos',
    celulares: 'celulares',
    backUps: 'backUps',
    equipos_tercerizado: 'equipos_tercerizado',
    boletasReparacion: 'boletasReparacion',
  },
  ESTADO_BOLETAS: {
    pendiente:'pendiente',
    cancelado:'cancelado',
    en_revision:'en_revision',
    en_reparacion:'en_reparacion',
    reparado:'reparado',
    no_reparado:'no_reparado',
    para_notificar:'para_notificar',
    esperado_respuesta:'esperado_respuesta',
    para_entregar:'para_entregar',
    pausado:'pausado',
    retirado:'retirado',
  }
};
